# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 20 # pagination based on number of posts
paginate_path: "page:num"
highlighter: rouge
markdown: kramdown
disqus: mindbrave
gravatar: quetzacotll@gmail.com
google_analytics: UA-111664723-1
title: Mindbrave

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Mindbrave

description: Software craftmanship
author:
  name: Rafał Łużyński
  email: rafalluzynski0@gmail.com
  github: mindbrave
  twitter: quetzakubica
  bio: Software craftmanship enthusiast
  email_md5: 15531b6dca8b86f3c21db443150901fa

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

plugins:
  - jekyll-paginate
